- hosts: all
  tasks:
  - name: setting up docker yum conf
    yum_repository:
      name: docker
      description: desc for docker
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: no

  - name: Installing docker
    package:
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present
  - name: Install docker package
    pip:
      name: docker.py
